- hosts: all
  tasks:
  - name: "下载httpd"
    yum:
      name: httpd
      state: present
  - name: "创建网页测试文件"
    file:
      path: /var/www/html/index.html
      state: touch
      mode: 0644
  - name: "写入内容到index.html"
    lineinfile:
      path: /var/www/html/index.html
      regexp: "^"
      line: "test index.html"
  - name: "启动httpd"
    service:
      name: httpd
      state: started